/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasi_simpanpinjam.form;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.plaf.basic.BasicMenuBarUI;
import koperasi_simpanpinjam.Koperasi_SimpanPinjam;
import koperasi_simpanpinjam.control.LaporanController;

/**
 *
 * @author Candi-PC
 */

public class FormUtama extends javax.swing.JFrame {

    LaporanController lapCont=new LaporanController(Koperasi_SimpanPinjam.emf);
    String kd, nm, aks;
    
    /**
     * Creates new form FormUtama
     */
    
    public FormUtama(String kode, String nama, String akses) {
        initComponents();
        setLocationRelativeTo(null);
        jMenuBar1.setUI(new BasicMenuBarUI(){
            public void paint(Graphics g, JComponent c){
                g.setColor(new Color(217, 121, 37));
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
        kd=kode;
        nm=nama;
        aks=akses;
        txtNama.setText(nm);
        txtHakAkses.setText(aks);
        setLocationRelativeTo(null);
    }
    
    public JMenuItem menuAdmin(){
        return admin;
    }
    
    public JMenu menuSimpanan(){
        return Msimpanan;
    }
    
    public JMenu menuPinjaman(){
        return Mpinjaman;
    }
    
    public JMenu menuLaporan(){
        return laporan;
    }
    
    public JMenu menuLogin(){
        return login;
    }
    
    public JMenu menuMaster(){
        return master;
    }
    
    public JMenuItem menuAnggota(){
        return anggota;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHakAkses = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        anggota = new javax.swing.JMenuItem();
        Msimpanan = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        simpanan = new javax.swing.JMenuItem();
        Mpinjaman = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        lapuser = new javax.swing.JMenuItem();
        lapdaftar = new javax.swing.JMenuItem();
        lapsimpanan = new javax.swing.JMenuItem();
        lappinjaman = new javax.swing.JMenuItem();
        lappinjaman1 = new javax.swing.JMenuItem();
        lappinjaman2 = new javax.swing.JMenuItem();
        login = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(1, 52, 64));

        jLabel1.setBackground(new java.awt.Color(239, 231, 190));
        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 231, 190));
        jLabel1.setText("Nama:");

        txtNama.setBackground(new java.awt.Color(239, 231, 190));
        txtNama.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(239, 231, 190));
        txtNama.setText("Nama");

        jLabel3.setBackground(new java.awt.Color(239, 231, 190));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 231, 190));
        jLabel3.setText("Hak Akses:");

        txtHakAkses.setBackground(new java.awt.Color(239, 231, 190));
        txtHakAkses.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        txtHakAkses.setForeground(new java.awt.Color(239, 231, 190));
        txtHakAkses.setText("Hak Akses");

        jPanel2.setLayout(new java.awt.CardLayout());

        DesktopPane.setBackground(new java.awt.Color(0, 38, 53));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        jPanel2.add(DesktopPane, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNama)
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHakAkses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtHakAkses))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNama)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(217, 121, 37));
        jMenuBar1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuBar1.setOpaque(false);

        master.setForeground(new java.awt.Color(239, 231, 190));
        master.setText("Master");
        master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        master.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        admin.setBackground(new java.awt.Color(217, 121, 37));
        admin.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(239, 231, 190));
        admin.setText("Admin");
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setOpaque(true);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        master.add(admin);

        anggota.setBackground(new java.awt.Color(217, 121, 37));
        anggota.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        anggota.setForeground(new java.awt.Color(239, 231, 190));
        anggota.setText("Anggota");
        anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota.setOpaque(true);
        anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaActionPerformed(evt);
            }
        });
        master.add(anggota);

        jMenuBar1.add(master);

        Msimpanan.setForeground(new java.awt.Color(239, 231, 190));
        Msimpanan.setText("Simpanan");
        Msimpanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Msimpanan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        jMenuItem4.setBackground(new java.awt.Color(217, 121, 37));
        jMenuItem4.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(239, 231, 190));
        jMenuItem4.setText("Buka Akun Simpanan");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.setOpaque(true);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Msimpanan.add(jMenuItem4);

        simpanan.setBackground(new java.awt.Color(217, 121, 37));
        simpanan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        simpanan.setForeground(new java.awt.Color(239, 231, 190));
        simpanan.setText("Transaksi Simpanan");
        simpanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanan.setOpaque(true);
        simpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpananActionPerformed(evt);
            }
        });
        Msimpanan.add(simpanan);

        jMenuBar1.add(Msimpanan);

        Mpinjaman.setForeground(new java.awt.Color(239, 231, 190));
        Mpinjaman.setText("Pinjaman");
        Mpinjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mpinjaman.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(217, 121, 37));
        jMenuItem1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(239, 231, 190));
        jMenuItem1.setText("Akun Pinjaman");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Mpinjaman.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(217, 121, 37));
        jMenuItem2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(239, 231, 190));
        jMenuItem2.setText("Transaksi Pinjaman");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Mpinjaman.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(217, 121, 37));
        jMenuItem3.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(239, 231, 190));
        jMenuItem3.setText("Angsuran Pinjaman");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Mpinjaman.add(jMenuItem3);

        jMenuBar1.add(Mpinjaman);

        laporan.setForeground(new java.awt.Color(239, 231, 190));
        laporan.setText("Laporan");
        laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        lapuser.setBackground(new java.awt.Color(217, 121, 37));
        lapuser.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lapuser.setForeground(new java.awt.Color(239, 231, 190));
        lapuser.setText("Laporan Admin");
        lapuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapuser.setOpaque(true);
        lapuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapuserActionPerformed(evt);
            }
        });
        laporan.add(lapuser);

        lapdaftar.setBackground(new java.awt.Color(217, 121, 37));
        lapdaftar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lapdaftar.setForeground(new java.awt.Color(239, 231, 190));
        lapdaftar.setText("Laporan Anggota");
        lapdaftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapdaftar.setOpaque(true);
        lapdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapdaftarActionPerformed(evt);
            }
        });
        laporan.add(lapdaftar);

        lapsimpanan.setBackground(new java.awt.Color(217, 121, 37));
        lapsimpanan.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lapsimpanan.setForeground(new java.awt.Color(239, 231, 190));
        lapsimpanan.setText("Laporan Akun Simpan");
        lapsimpanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapsimpanan.setOpaque(true);
        lapsimpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapsimpananActionPerformed(evt);
            }
        });
        laporan.add(lapsimpanan);

        lappinjaman.setBackground(new java.awt.Color(217, 121, 37));
        lappinjaman.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lappinjaman.setForeground(new java.awt.Color(239, 231, 190));
        lappinjaman.setText("Laporan Akun Pinjam");
        lappinjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lappinjaman.setOpaque(true);
        lappinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lappinjamanActionPerformed(evt);
            }
        });
        laporan.add(lappinjaman);

        lappinjaman1.setBackground(new java.awt.Color(217, 121, 37));
        lappinjaman1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lappinjaman1.setForeground(new java.awt.Color(239, 231, 190));
        lappinjaman1.setText("Laporan Transaksi Simpanan");
        lappinjaman1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lappinjaman1.setOpaque(true);
        lappinjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lappinjaman1ActionPerformed(evt);
            }
        });
        laporan.add(lappinjaman1);

        lappinjaman2.setBackground(new java.awt.Color(217, 121, 37));
        lappinjaman2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        lappinjaman2.setForeground(new java.awt.Color(239, 231, 190));
        lappinjaman2.setText("Laporan Angsuran Pinjaman");
        lappinjaman2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lappinjaman2.setOpaque(true);
        lappinjaman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lappinjaman2ActionPerformed(evt);
            }
        });
        laporan.add(lappinjaman2);

        jMenuBar1.add(laporan);

        login.setForeground(new java.awt.Color(239, 231, 190));
        login.setText("Logout");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jMenuBar1.add(login);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        user us=new user();
        showForm(us);
    }//GEN-LAST:event_adminActionPerformed

    private void simpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpananActionPerformed
        Fsimpan sim=new Fsimpan(kd);
        showForm(sim);
    }//GEN-LAST:event_simpananActionPerformed

    private void anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaActionPerformed
        anggota ag=new anggota();
        showForm(ag);
    }//GEN-LAST:event_anggotaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        akun_simpan as=new akun_simpan();
        showForm(as);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        akun_pinjam ap=new akun_pinjam();
        showForm(ap);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        pinjam p=new pinjam(kd);
        showForm(p);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        angsuran_pinjam ap=new angsuran_pinjam(kd);
        showForm(ap);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        FormLogin log=new FormLogin();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void lappinjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lappinjaman1ActionPerformed
        lapCont.cetakTransaksiSimpanan();
    }//GEN-LAST:event_lappinjaman1ActionPerformed

    private void lapuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapuserActionPerformed
        lapCont.cetakUser();
    }//GEN-LAST:event_lapuserActionPerformed

    private void lapdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapdaftarActionPerformed
        lapCont.cetakAnggota();
    }//GEN-LAST:event_lapdaftarActionPerformed

    private void lapsimpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapsimpananActionPerformed
        lapCont.cetakAkunSimpanan();
    }//GEN-LAST:event_lapsimpananActionPerformed

    private void lappinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lappinjamanActionPerformed
        lapCont.cetakAkunPinjaman();
    }//GEN-LAST:event_lappinjamanActionPerformed

    private void lappinjaman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lappinjaman2ActionPerformed
        lapCont.cetakAngsuranPinjaman();
    }//GEN-LAST:event_lappinjaman2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama(this.toString(), this.toString(), this.toString()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu Mpinjaman;
    private javax.swing.JMenu Msimpanan;
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenuItem anggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem lapdaftar;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem lappinjaman;
    private javax.swing.JMenuItem lappinjaman1;
    private javax.swing.JMenuItem lappinjaman2;
    private javax.swing.JMenuItem lapsimpanan;
    private javax.swing.JMenuItem lapuser;
    private javax.swing.JMenu login;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem simpanan;
    private javax.swing.JLabel txtHakAkses;
    private javax.swing.JLabel txtNama;
    // End of variables declaration//GEN-END:variables

NavigatorFormInt nav;
private void showForm(Object obj){
    JInternalFrame jf = null;
    jf =(JInternalFrame) obj;
    DesktopPane.add(jf);
    jf.setVisible(true);
    try{
        jf.setMaximum(true);
        jf.setSelected(true);
    }catch(java.beans.PropertyVetoException e){}
}
}
